const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("electronAPI", {
  minimizeWindow: () => ipcRenderer.invoke("minimize-window"),
  suppressBlurHide: (ms) => ipcRenderer.invoke("suppress-blur-hide", ms),
  setBlurHideLocked: (locked) => ipcRenderer.invoke("set-blur-hide-locked", locked),
  listSafetySnapshots: () => ipcRenderer.invoke("list-safety-snapshots"),
  restoreLatestSafetySnapshot: () => ipcRenderer.invoke("restore-latest-safety-snapshot"),
  copyPastePrompt: (text) => ipcRenderer.invoke("copy-paste-prompt", text),
  writeClipboard: (text) => ipcRenderer.invoke("write-clipboard", text),
  openAccessibilitySettings: () => ipcRenderer.invoke("open-accessibility-settings"),
  openAutomationSettings: () => ipcRenderer.invoke("open-automation-settings"),
  getPermissionDiagnostics: () => ipcRenderer.invoke("get-permission-diagnostics"),
  getAppInfo: () => ipcRenderer.invoke("get-app-info"),
  getHotkeyInfo: () => ipcRenderer.invoke("get-hotkey-info"),
  cycleGlobalHotkey: () => ipcRenderer.invoke("cycle-global-hotkey"),
  pinActiveGlobalHotkey: () => ipcRenderer.invoke("pin-active-global-hotkey"),
  setPreferredGlobalHotkey: (accelerator) =>
    ipcRenderer.invoke("set-preferred-global-hotkey", accelerator),
  getOpenAtLogin: () => ipcRenderer.invoke("get-open-at-login"),
  setOpenAtLogin: (enabled) => ipcRenderer.invoke("set-open-at-login", enabled),
  chooseExportFormat: () => ipcRenderer.invoke("choose-export-format"),
  exportPrompts: (payload) => ipcRenderer.invoke("export-prompts", payload),
  importPrompts: () => ipcRenderer.invoke("import-prompts"),
  chooseImportMode: (payload) => ipcRenderer.invoke("choose-import-mode", payload),
  showNotification: (payload) => ipcRenderer.invoke("show-notification", payload),
  getPrompts: () => ipcRenderer.invoke("get-prompts"),
  setPrompts: (prompts) => ipcRenderer.invoke("set-prompts", prompts),
  getHiddenTags: () => ipcRenderer.invoke("get-hidden-tags"),
  setHiddenTags: (tags) => ipcRenderer.invoke("set-hidden-tags", tags),
  getWebdavConfig: () => ipcRenderer.invoke("webdav-get-config"),
  setWebdavConfig: (config) => ipcRenderer.invoke("webdav-set-config", config),
  testWebdav: () => ipcRenderer.invoke("webdav-test"),
  backupWebdav: () => ipcRenderer.invoke("webdav-backup"),
  restoreWebdavLatest: () => ipcRenderer.invoke("webdav-restore-latest"),
  restoreWebdavPath: (path) => ipcRenderer.invoke("webdav-restore-path", path),
  listWebdavBackups: () => ipcRenderer.invoke("webdav-list-backups"),
  getWebdavSettings: () => ipcRenderer.invoke("webdav-get-settings"),
  setWebdavSettings: (settings) => ipcRenderer.invoke("webdav-set-settings", settings),
  onFocusSearch: (handler) => ipcRenderer.on("focus-search", handler),
  onManageLayerBlocksHide: (handler) => ipcRenderer.on("manage-layer-blocks-hide", handler),
  onPrepareQuit: (handler) => ipcRenderer.on("prepare-quit", handler),
  prepareQuitDone: () => ipcRenderer.send("prepare-quit-done"),
  onAutoBackup: (handler) => ipcRenderer.on("auto-backup", (_e, fileName) => handler(fileName)),
});
